//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbdistribuidorafyjEntities : DbContext
    {
        public dbdistribuidorafyjEntities()
            : base("name=dbdistribuidorafyjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Informe> Informe { get; set; }
        public virtual DbSet<LineaPedido> LineaPedido { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<BodegaProducto> BodegaProducto { get; set; }
    }
}
